language: cpp

sudo: true

compiler:
  - gcc-4.8

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt486 -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq opt-qt4-qmake opt-qt4-dev-tools
  - source /opt/qt-4.8/bin/qt-4.8-env.sh

script:
        - qmake -recursive STA.pro
        - make
