language: c++

addons:
  apt:
    sources:
    - kubuntu-backports
    - ubuntu-toolchain-r-test
    packages:
    - qt4-x11-4.8.2
    - gcc-4.8

compiler:
  gcc-4.8

script:
        - qmake -recursive STA.pro
        - make
