language: c++

sudo: true

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt486 -y
  - sudo add-apt-repository ppa:h-rayflood/gcc-upper -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq opt-qt4-qmake opt-qt4-dev-tools g++-4.8
  - source /opt/qt-4.8/bin/qt-4.8-env.sh
  - sudo ln -s /usr/lib/x86_64-linux-gnu/ /usr/lib/i386-linux-gnu
  - sudo rm -f /usr/bin/gcc
  - sudo rm -f /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

script:
  - gcc --version
  - g++ --version
  - qmake -recursive STA.pro
  - make CXXFLAGS+=-fpermissive 
