language: c++

addons:
  apt:
    sources:
    - debian-sid
    - ubuntu-toolchain-r-test
    packages:
    - qt4-default
    - gcc-4.8

compiler:
  gcc-4.8

script:
        - qmake -recursive STA.pro
        - make
