language: c++

sudo: true

before_script:
  - sudo add-apt-repository ppa:kubuntu-backports -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r-test -y
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt4-x11 gcc-4.8

compiler:
  gcc-4.8

script:
        - qmake -recursive STA.pro
        - make
